import { Inter } from 'next/font/google'
import './globals.css';
import { Providers } from "../redux/providers.js";
import QueryProviders from '@/utils/QueryProviders.js';
 
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
 
    <html lang="en">
      <body className={inter.className}>
          <QueryProviders>
            <Providers>
              {children}
              <div id='photo-picker-element'></div>
            </Providers>
          </QueryProviders>

      </body>
    </html>
 
  )
}
